set(${PROJECT_NAME}_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(${PROJECT_NAME}_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(${PROJECT_NAME}_VERSION_TWEAK ${PROJECT_VERSION_TWEAK})

configure_file (
    "${PROJECT_SOURCE_DIR}/${PROJECT_NAME_LOWER}_config.h.in"
    "${PROJECT_BINARY_DIR}/${PROJECT_NAME_LOWER}_config.h"
)

include_directories(${PROJECT_BINARY_DIR})
